export const initialData = {
  meta: {
    teamName: "FPC Media Missions Creatives",
    mission:
      "Use photography, video, design, and digital storytelling to glorify Jesus Christ, preserve what God is doing in the church, invite people into fellowship, and help the message reach beyond the walls of the building.",
    driveRootId: process.env.NEXT_PUBLIC_DEFAULT_DRIVE_FOLDER_ID || "root",
  },

  postRhythm: [
    {
      id: "sun-regular",
      day: "Sunday Morning",
      time: "12:30 PM",
      title: "Regular post",
      shoot: "Church-related interactive content, sermon recap recordings, photos of other ministries.",
      postProduction: "Editor assigned per video.",
      platforms: ["Instagram", "Facebook"],
      status: "Recurring",
      color: "sky",
    },
    {
      id: "sun-worship",
      day: "Sunday Evening",
      time: "8:00 PM",
      title: "Worship recap",
      shoot: "Live recordings, mainly worship and specials.",
      postProduction: "Editor assigned per video.",
      platforms: ["Instagram Reels", "Facebook"],
      status: "Needs footage",
      color: "violet",
    },
    {
      id: "mon-sermon",
      day: "Monday",
      time: "8:00 PM",
      title: "Sermon recap",
      shoot: "No new shoot.",
      postProduction: "Editor assigned per video.",
      platforms: ["Instagram", "Facebook", "YouTube Shorts"],
      status: "Needs edit",
      color: "orange",
    },
    {
      id: "tue-engage",
      day: "Every other Tuesday",
      time: "11:30 AM",
      title: "Engaging post",
      shoot: "Use member, guest, or church community interaction content.",
      postProduction: "Editor assigned per video.",
      platforms: ["Instagram", "Facebook"],
      status: "Idea needed",
      color: "emerald",
    },
    {
      id: "wed-invite",
      day: "Wednesday",
      time: "11:30 AM",
      title: "Come to church tonight",
      shoot: "Wednesday service pictures almost always unless told otherwise.",
      postProduction: "Editor assigned per video.",
      platforms: ["Instagram", "Facebook"],
      status: "Recurring",
      color: "blue",
    },
    {
      id: "sat-invite",
      day: "Saturday",
      time: "11:30 AM",
      title: "Come to church tonight",
      shoot: "No new shoot.",
      postProduction: "Use available video or regular graphic.",
      platforms: ["Instagram", "Facebook"],
      status: "Recurring",
      color: "rose",
    },
  ],

  contentCategories: [
    {
      id: "highlights",
      title: "Highlights",
      description: "Clips or visuals taken from services and special moments.",
      types: [
        { name: "Worship Highlights", description: "Worship moments from Sunday evening, Wednesday services, or special services." },
        { name: "Special Highlights", description: "Special songs, guest moments, presentations, or unique service moments." },
        { name: "Sermon Highlights", description: "Short clips from preaching or teaching moments." },
        { name: "Altar Call Highlight", description: "Moments from altar call, prayer, response, or ministry time." },
      ],
    },
    {
      id: "promotional",
      title: "Promotional",
      description: "Posts that invite people, promote ministries, and bring awareness to events.",
      types: [
        { name: "Service Promotion", description: "Posts inviting people to upcoming services, such as Wednesday night or Saturday night reminders." },
        { name: "Ministry Promotion", description: "Posts highlighting different ministries in the church." },
        { name: "Event Promotion", description: "Posts promoting upcoming church events, special services, or programs." },
      ],
    },
    {
      id: "engagement",
      title: "Engagement",
      description: "Posts designed to connect with people, encourage interaction, and highlight the church community.",
      types: [
        { name: "Public Interactions", description: "Interactive content with members, guests, or the church community." },
        { name: "Testimonial", description: "Testimonies or personal stories from people in the church." },
        { name: "Appreciations", description: "Posts appreciating leaders, volunteers, ministries, members, or special contributors." },
      ],
    },
  ],

  videoIdeas: [
    {
      id: "life-five-year-old",
      title: "A Sunday in the life of a five-year-old on the Social Media team",
      priority: "Top",
      notes: "Recreate first. Remove after recorded.",
      status: "Ready",
    },
    {
      id: "ig-dxkju",
      title: "Instagram reference: DXkju01km4E",
      priority: "Reference",
      notes: "Use as format inspiration.",
      status: "Queued",
    },
    {
      id: "ig-dxroz",
      title: "Instagram reference: DXRoz5MviHu",
      priority: "Reference",
      notes: "Use as format inspiration.",
      status: "Queued",
    },
    {
      id: "missionstudents",
      title: "weare_missionstudents reference",
      priority: "Reference",
      notes: "Review tone, cuts, framing, and structure.",
      status: "Queued",
    },
  ],

  folderTemplates: [
    {
      id: "sunday-service",
      title: "Sunday Service Folder",
      description: "Full structure for Sunday morning/evening capture and posting.",
      folders: ["01 Raw Footage", "02 Photos", "03 Sermon Clips", "04 Worship Recap", "05 Graphics", "06 Captions", "07 Exports", "08 Posted"],
    },
    {
      id: "wednesday-service",
      title: "Wednesday Service Folder",
      description: "Fast structure for midweek service and invite content.",
      folders: ["01 Photos", "02 Short Clips", "03 Invite Post", "04 Sermon Moments", "05 Exports"],
    },
    {
      id: "event-promotion",
      title: "Event Promotion Folder",
      description: "Assets, edits, and final exports for special events.",
      folders: ["01 Planning", "02 Brand Assets", "03 Graphics", "04 Raw Media", "05 Edits", "06 Final Exports", "07 Posted"],
    },
    {
      id: "ministry-feature",
      title: "Ministry Feature Folder",
      description: "For highlighting a ministry, leader, volunteer, or testimony.",
      folders: ["01 Interview Notes", "02 Photos", "03 B-Roll", "04 Edit", "05 Captions", "06 Exports"],
    },
  ],

  playbooks: [
    {
      id: "sunday-capture",
      title: "Sunday Morning Capture",
      purpose: "Capture the life of the church without interrupting the service.",
      progress: {},
      steps: [
        "Check batteries, storage, lenses, and audio before service.",
        "Capture lobby, guest, and church-family interaction moments.",
        "Record worship wide shots, close shots, musicians, and response.",
        "Capture sermon moments with clean framing and stable camera movement.",
        "Mark at least three sermon quote moments for recap editing.",
        "Capture other ministries when appropriate.",
        "Upload raw media to the correct Drive folder before leaving if possible.",
      ],
    },
    {
      id: "worship-recap",
      title: "Worship Recap Workflow",
      purpose: "Turn worship/special moments into a clean, reverent recap.",
      progress: {},
      steps: [
        "Choose one strong worship or special-song moment.",
        "Find clean visual sections with emotion, reverence, and focus.",
        "Avoid awkward transitions, distracting cuts, or poor audio sections.",
        "Export vertical 9:16 version first.",
        "Upload final export into the Drive Exports folder.",
        "Schedule Sunday 8:00 PM unless directed otherwise.",
      ],
    },
    {
      id: "sermon-recap",
      title: "Sermon Recap Workflow",
      purpose: "Help the message reach beyond the building.",
      progress: {},
      steps: [
        "Choose a short, clear, strong preaching/teaching moment.",
        "Make sure the clip works even for someone who was not in service.",
        "Caption the clip clearly.",
        "Export vertical version for social platforms.",
        "Add title/caption idea to the post item.",
        "Schedule Monday 8:00 PM.",
      ],
    },
    {
      id: "service-promotion",
      title: "Service Promotion",
      purpose: "Invite people warmly and clearly.",
      progress: {},
      steps: [
        "Use current, high-quality photo or short clip.",
        "Keep the message simple and inviting.",
        "Mention service time clearly.",
        "Post Wednesday or Saturday at 11:30 AM.",
        "Check spelling, time, and platform crop before posting.",
      ],
    },
  ],

  gear: [
    {
      id: "main-camera",
      name: "Main Camera",
      category: "Camera",
      status: "Ready",
      location: "Media booth",
      owner: "Media team",
      settings: [
        { label: "Resolution", value: "4K" },
        { label: "Frame Rate", value: "24fps" },
        { label: "Shutter", value: "1/50" },
        { label: "White Balance", value: "Set on location" },
        { label: "Use", value: "Sermon / worship / general capture" },
      ],
      notes: "Confirm exact model-specific settings after camera configs are finalized.",
    },
    {
      id: "recap-camera",
      name: "Motion / Recap Camera",
      category: "Camera",
      status: "Check battery",
      location: "Media cabinet",
      owner: "Media team",
      settings: [
        { label: "Resolution", value: "4K" },
        { label: "Frame Rate", value: "60fps" },
        { label: "Shutter", value: "1/125" },
        { label: "Use", value: "Worship movement, b-roll, short-form shots" },
      ],
      notes: "Use for smoother slow-motion edits when appropriate.",
    },
    {
      id: "livestream",
      name: "Livestream System",
      category: "Broadcast",
      status: "Ready",
      location: "Media booth",
      owner: "Media team",
      settings: [
        { label: "Resolution", value: "1080p" },
        { label: "Audio", value: "Board feed" },
        { label: "Check", value: "10 minutes before service" },
        { label: "Platforms", value: "YouTube / Facebook" },
      ],
      notes: "Always confirm audio and stream health before service begins.",
    },
    {
      id: "sd-cards",
      name: "SD Cards / Storage",
      category: "Storage",
      status: "Needs check",
      location: "Media cabinet",
      owner: "Media team",
      settings: [
        { label: "Before service", value: "Format after backup" },
        { label: "After service", value: "Upload to Drive" },
        { label: "Rule", value: "Never format until confirmed backed up" },
      ],
      notes: "This app should become the source of truth for storage workflow.",
    },
  ],

  access: [
    {
      id: "instagram",
      name: "Instagram",
      category: "Social",
      username: "Add username",
      password: "Add password",
      notes: "Reels, stories, reminders, recaps.",
    },
    {
      id: "facebook",
      name: "Facebook",
      category: "Social",
      username: "Add username",
      password: "Add password",
      notes: "Church posts and livestream/archive support.",
    },
    {
      id: "youtube",
      name: "YouTube",
      category: "Video",
      username: "Add username",
      password: "Add password",
      notes: "Livestream, archives, shorts, and teaching content.",
    },
    {
      id: "design",
      name: "Design Software",
      category: "Software",
      username: "Add username",
      password: "Add password",
      notes: "Graphics, templates, captions, exports.",
    },
  ],

  team: [
    {
      id: "promotions-lead",
      name: "Promotions Lead",
      role: "Direction / posting / systems",
      focus: "Keep creative work organized, efficient, excellent, and mission-aligned.",
      status: "Active",
    },
    {
      id: "editor",
      name: "Assigned Editor",
      role: "Post-production",
      focus: "Assigned per video for now until workflow expands.",
      status: "Weekly assignment",
    },
    {
      id: "camera-op",
      name: "Camera Operator",
      role: "Capture",
      focus: "Wednesday, Sunday morning, Sunday evening.",
      status: "Needs schedule",
    },
  ],
};
